### ISSUE TITLE
using blend.cpp

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky-tools#1]
I have a lot of free time coming up so I was going to tackle the running lights from the 21 November blog post. The link there lead to the blend.cpp but I am uncertain on how it is meant to be used, or if there is an even easier way to do it.

**Comment by endless-sky** [comment]
It's a command line program that you'll need to compile; the first line is the command you would use on Linux to compile it.

The issue is that you need to be able to save a PNG image that has color values even for the transparent pixels. It's possible you can find a program that does that. (GIMP claims to be able to, but doesn't seem to give you a way to edit the color of transparent pixels in the first place.)

**Comment by jafdy** [comment]
Any advice or direction you can give would be helpful as I only really have a load of ideas to work with at the moment. Don't feel rushed, I also want to get a set of recoloring mods for colorblind users.

**Comment by jafdy** [comment]
I'm completely out of my depths here, having never compiled anything successfully and not really having any idea how to do this otherwise (also I'm a windows user).

**Comment by jafdy** [comment]
I have found a different way that I can manage. [This is what I did with the star barge](https://media.giphy.com/media/12rnSzf4jy19DO/giphy.gif) Hopefully the moving textures will not be noticeable once it is shrunk. 
Without a better knowledge of Gimp the only way that (I think) I could use to sort this out is to just recreate  each of the original sprites as I go.
Edit: Got a trial for the Vanguard as well. https://media.giphy.com/media/3KMK3u2gKV59C/giphy.gif
